name: Build docs
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get python versions
        uses: chris48s/satisfying-python
        id: python-versions

      - name: Set up Python ${{ steps.hello-world.outputs.min}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.hello-world.outputs.min}}

      - name: Show python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Build docs
        run: |
          make build-docs
